name: MkDocs CI

on:
  push:
    paths:
      - "**/*.md"
      - "mkdocs.yml"
      - "docs/**"
      - "books/**"
      - "requirements.txt"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Build site (no deploy)
        run: mkdocs build --strict --verbose

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
